name: test_POI

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths: 
      - apis/poi/**
      - .github/workflows/test_POI.yml
  pull_request:
    branches: [ main ]
    paths:
      - apis/poi/**
      - .github/workflows/test_POI.yml

jobs:

  build:  
    env:
      path: apis/poi/
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.x
    - name: Restore dependencies
      run: dotnet restore ${{env.path}}
    - name: Build
      run: dotnet build --no-restore  ${{env.path}}
    - name: Test
      run: dotnet test --no-build --verbosity normal ${{env.path}}
        
  deploy:    
    needs: build
    if: github.ref == 'refs/heads/main'
    env: 
      acr: openhackbvx30gp2acr.azurecr.io
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Build and push
      run: |
        cd apis/poi/web
        docker login ${{env.acr}} --username ${{ secrets.ACR_USERNAME }} --password ${{ secrets.ACR_PASSWORD }}
        docker build . -t ${{env.acr}}/devopsoh/api-poi:${{ github.sha }}
        docker push ${{env.acr}}/devopsoh/api-poi:${{ github.sha }} 

    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'openhackbvx30gp2poi'
        publish-profile: ${{ secrets.AzureWebAppPublishProfileStaging }}
        images: ${{env.acr}}/devopsoh/api-poi:${{ github.sha }}
        slot-name: staging
    
  swap:
    needs: deploy
    if: github.ref == 'refs/heads/main'
    env:
      staging-url: https://openhackbvx30gp2poi-staging.azurewebsites.net
      warmup-path: /api/healthcheck/poi
    runs-on: ubuntu-latest
    steps:    
    - name: Waiting Warm Up
      run: |
        for ((i=1;i<=1500;i++))
        do
        status_code=$(curl -L ${{env.staging-url}}${{warmup-path}} -w '%{http_code}\n' -s)
        if [[ $status_code == *"200" ]] ; then
        echo -e " \e[32m $status_code"
        else
        echo -e " \e[31m $status_code"
        fi
        sleep 0.300
        done
      shell: bash
    - name: Swap
      run: |
        echo 'done'

  
    
