name: Go

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - apis/trips/**
      - .github/workflows/test_trips.yml
  pull_request:
    branches: [ main ]
    paths:
      - apis/trips/**
      - .github/workflows/test_trips.yml
env: 
      working-directory: api/trips/
jobs:
  
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go      
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      working-directory: ${{ env.working-directory }}
      run: go build -v

    - name: Test
      working-directory: ${{ env.working-directory }}
      run: go test -v ./tests
