name: test_POI

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths: 
      - apis/poi/**
      - .github/workflows/test_POI.yml
  pull_request:
    branches: [ main ]
    paths:
      - apis/poi/**
      - .github/workflows/test_POI.yml

jobs:

  build:  
    env:
      path: apis/poi/
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.x
    - name: Restore dependencies
      run: dotnet restore ${{env.path}}
    - name: Build
      run: dotnet build --no-restore  ${{env.path}}
    - name: Test
      run: dotnet test --no-build --verbosity normal ${{env.path}}
      
  sonarcloud:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      with:
        projectBaseDir: ./apis/poi/
        args: >
          -Dsonar.organization=ci-back-to-basis
          -Dsonar.projectKey=openhack-t12
          -Dsonar.tests=tests/
          -Dsonar.verbose=true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        
  deploy:    
    needs: sonarcloud
    if: github.ref == 'refs/heads/main'
    env: 
      acr: openhackbvx30gp2acr.azurecr.io
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Build and push
      run: |
        cd apis/poi/web
        docker login ${{env.acr}} --username ${{ secrets.ACR_USERNAME }} --password ${{ secrets.ACR_PASSWORD }}
        docker build . -t ${{env.acr}}/devopsoh/api-poi:${{ github.sha }}
        docker push ${{env.acr}}/devopsoh/api-poi:${{ github.sha }} 

    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'openhackbvx30gp2poi'
        publish-profile: ${{ secrets.AzureWebAppPublishProfileStaging }}
        images: ${{env.acr}}/devopsoh/api-poi:${{ github.sha }}
        slot-name: staging
    
  swap:
    needs: deploy
    if: github.ref == 'refs/heads/main'
    env:
      staging-url: https://openhackbvx30gp2poi-staging.azurewebsites.net
      prod-url: https://openhackbvx30gp2poi.azurewebsites.net
      warmup-path: /api/healthcheck/poi
      resource-group: openhackbvx30gp2rg
      app-service: openhackbvx30gp2poi
    runs-on: ubuntu-latest
    steps: 
    - name: azLog
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS_POI }}
        environment: 'AzureStack'
    - name: Start staging
      run: |
        az webapp start -g ${{env.resource-group}} -n ${{env.app-service}} --slot staging
    - name: Check deploy service URL | Validate staging
      uses: Jtalk/url-health-check-action@v1.5
      with:        
        url: ${{env.staging-url}}${{env.warmup-path}}        
        max-attempts: 3        
        retry-delay: 30s
   
    - name: SWAP
      run: | 
          az webapp deployment slot swap  -g ${{env.resource-group}} -n ${{env.app-service}} --slot staging --target-slot production
    - name: Check production URL
      uses: Jtalk/url-health-check-action@v1.5
      with:        
        url: ${{env.prod-url}}${{env.warmup-path}}        
        max-attempts: 3        
        retry-delay: 30s
    - name: Rollback
      if: ${{ failure() }}
      run: | 
          az webapp deployment slot swap  -g ${{env.resource-group}} -n ${{env.app-service}} --slot staging --target-slot production
    - name: Stop staging
      run: |
        az webapp stop -g ${{env.resource-group}} -n ${{env.app-service}} --slot staging 

    
    
