name: test_POI

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths: 
      - apis/poi/**
      - .github/workflows/test_POI.yml
  pull_request:
    branches: [ main ]
    paths:
      - apis/poi/**
      - .github/workflows/test_POI.yml

jobs:

  build:
  
    env:
      path: apis/poi/
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.x
    - name: Restore dependencies
      run: dotnet restore ${path}
    - name: Build
      run: dotnet build --no-restore  ${path}
    - name: Test
      run: dotnet test --no-build --verbosity normal ${path}
    - name: Workflow error
      if: failure() 
      uses: JasonEtco/create-an-issue@v2.4.0
