name: WorkflowFails
on: 
  workflow_run:  
    workflows: ["maven", "test_POI", "test_trips", "test_userprofile"]
    types: [completed]    
jobs:  
  error:
    runs-on: ubuntu-latest
    steps:
      - uses: JasonEtco/create-an-issue@v2
        if: ${{ github.event.workflow_run.conclusion == 'failure' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
